### ISSUE TITLE
POINTN causing None error

### ISSUE THREAD

**Issue by kristyhoran** [MDU-PHL/abritamr#18]
When using the `--species` flag with `Staphylococcus_aureus` The following error was raised.
```
Traceback (most recent call last):
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/bin/abritamr", line 8, in <module>
    sys.exit(main())
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/abritamr.py", line 127, in main
    args.func(args)
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/abritamr.py", line 20, in run_pipeline
    collated_data = C.run()
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/Collate.py", line 296, in run
    summary_drugs, summary_partial, virulence = self._batch_collate(input_file = self.input)
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/Collate.py", line 277, in _batch_collate
    temp_match, temp_partial, temp_virulence = self.collate(prefix = prefix)
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/Collate.py", line 246, in collate
    reftab=reftab, df=df, isolate=prefix
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/Collate.py", line 143, in get_per_isolate
    partials = self.joins(dict_for_joining=partials)
  File "/home/morjm/miniconda3/envs/bohra200522_cloned_060622/lib/python3.7/site-packages/abritamr/Collate.py", line 41, in joins
    dict_for_joining[i] = ",".join(dict_for_joining[i])
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by kristyhoran** [comment]
Investigation of the offending sequence using assemblies generated with a range of assemblers revealed that a point mutation `23S_C2220T` indicating linezolid resistance is identified with a POINTN method. This led to a  `None` value being returned in the `setup_dict` on line 138.
